menu/urls.py
from django.urls import path, reverse_lazy
from .views import Homepage, HomeRegioes, DetalhesRegiao, PesquisaRegiao, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('regioes/', HomeRegioes.as_view(), name='homeregioes'),
    path('regioes/<int:pk>', DetalhesRegiao.as_view(), name='detalhesregiao'),
    path('pesquisa/', PesquisaRegiao.as_view(), name='pesquisaregiao'),
    path('login/', auth_view.LoginView.as_view(template_name='Login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='Logout.html'), name='logout'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('menu:homeregioes')), name='mudarsenha'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name="criarconta"),
]

webmenu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

LISTA_CATEGORIAS = (
    ("Brasil", "Brasil"),
    ("Mexico", "Mexico"),
    ("Arabe", "Arabe"),
    ("Japao", "Japao"),
    ("Argentina", "Argentina"),
    ("Coreia", "Coreia"),
    ("OUTROS", "Outros"),
)

MACRO_REGIOES = (
    ("AMERICA_SUL", "América do Sul"),
    ("AMERICA_NORTE", "América do Norte"),
    ("AMERICA_CENTRAL", "América Central"),
    ("ASIA", "Ásia"),
    ("AFRICA", "África"),
    ("ARABIA", "Arábia "),
    ("OUTROS", "Outros"),
)
class Regiao(models.Model):
    nome_regiao = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_regioes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=10, choices=LISTA_CATEGORIAS)
    macro_regiao = models.CharField(max_length=30, choices=MACRO_REGIOES, default='OUTROS')
    acessos = models.IntegerField(default=0)
    data_criacao=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nome_regiao

class Prato(models.Model):
    #Recomenda-se inserir o campo chave estrangeira como primeiro campo da classe por causa das migrações.
    regiao = models.ForeignKey("Regiao", related_name="pratos", on_delete=models.CASCADE)
    #CharField é um campo curto
    nome_prato = models.CharField(max_length=100)
    #O campo models.URLField é a definição de im link para um video.
    video = models.URLField()

    def __str__(self):
        return self.regiao.nome_regiao + " - " + self.nome_prato

# Criação da classe Usuario
class Usuario(AbstractUser):
    regioes_vistas = models.ManyToManyField("Regiao")
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

menu/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Usuario
from django import forms

class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

class LoginEmailForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))

menu/views.py
from django.shortcuts import redirect, reverse
from .models import Regiao, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('menu:homeregioes')
        else:
            return super().get(self, request, *args, **kwargs)

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('menu:login')
        else:
            return reverse('menu:criarconta')

class HomeRegioes(LoginRequiredMixin, ListView):
    template_name = "homeregioes.html"
    model = Regiao

class DetalhesRegiao(LoginRequiredMixin, DetailView):
    template_name = "detalhesregiao.html"
    model = Regiao
    # object -> 1 item do modelo

    def get_context_data(self, **kwargs):
        # Esta linha garante que o método get_context_data continue a executar suas funcionalidades
        context = super(DetalhesRegiao, self).get_context_data(**kwargs)
        regioes_relacionadas = Regiao.objects.filter(macro_regiao=self.get_object().macro_regiao).exclude(categoria=self.get_object().categoria)[0:5]
        context['regioes_relacionadas'] = regioes_relacionadas
        return context

    def get(self, request, *args, **kwargs):
        # Para descobrir qual Regiao o usuário está acessando, usa-se o método get_object()
        Regiao = self.get_object()
        # Somar uma unidade às acessos desta Regiao
        Regiao.acessos += 1
        # Salvar modificações feitas no banco de dados
        Regiao.save()
        # Resgatando o usuário que acesso um determinado Regiao
        usuario = request.user
        # Adicionando o Regiao acessado à lista de regioes visto
        # por um determinado usuário
        usuario.regioes_vistas.add(Regiao)
        # Redireciona o usuário à URL do Regiao desejado, ou seja, um Regiao na página detalhesRegiao.html
        return super().get(self, request, *args, **kwargs)

class PesquisaRegiao(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Regiao

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = Regiao.objects.filter(nome_regiao__icontains=termo_pesquisa)
            return object_list
        else:
            return None

class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('menu:homeregioes')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('menu:login')

menu/templates/detalhesregiao.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomeCardapio 
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
        <!-- 1ª Seção -->
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ object.nome_regiao }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ object.descricao|slice:":100" }}...
                </p>
                <div class="flex my-4">
                    <a href="{{ object.pratos.first.video }}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <!-- 2ª Seção -->
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Descrição
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        {{ object.descricao }}
                        <br>
                        Acessos: {{ object.acessos }}
                    </p>
                </div>

                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Pratos

                    </h2>
                    {% for prato in object.pratos.all %}
                        <h3 class='text-lg'>
                            <a href="{{ prato.video }}">
                            <p>Prato {{ forloop.counter }}: {{ prato.nome_prato }}</p>
                            </a>
                        </h3>
                    {% endfor %}
                </div>

            </div>
        </section>
        <!-- 3ª Seção -->
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for regiao in regioes_relacionadas %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                            <img src="{{ regiao.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

menu/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Editar Perfil
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('#');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.username }}</h2>

            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 text-white py-1 px-3 rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>IFSP</li>
        </ul>
    </footer>
{% endblock %}

menu/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomePage Mundo dos Sabores
{% endblock %}

{% block head %}
    <style>
        #id_email{
        width: 100%;
        color: #000000;
        padding: 5px 5px;
        }
        
    </style>
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/fundoQueijo.jpg' %}'); background-size: cover;">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Viaje pelo paladar, explore o Mundo dos Sabores!
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Sempre um restaurante perto de você!
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Venha conhecer nosso cardapio, coloque seu e-mail abaixo.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-gray-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Conhecer
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                    </a>
                </div>
            </div>
        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Desfrutes de sabores, dos mais diversos!
            </h2>
            <h5 class="md:text-xl text-lg">
                Tudo isso em um lugar, aconchegante e elegante.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/cozinha.jpg' %}" class="w-8/12" alt="Cozinha">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/restaurante.jpg' %}" class="w-8/12" alt="Restaurante">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Todos os sabores do mundo, em um só lugar.
            </h2>
            <h5 class="md:text-xl text-lg">
                Sempre com inovação e atenção aos detalhes para você.
            </h5>
        </div>

    </section>


    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Copywright: CAUÊ PACHECO PALMA, EDUARDO FERREIRA SILVA, LUCA VIANNA MARTINS SILVEIRA E PEDRO HENRIQUE NISHIMURA BACHAALANI  </li>
            <li>IFSP - Campus Bragança Paulista - SP</li>
        </ul>
    </footer>
{% endblock %}

menu/templates/homeregioes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Descubra Iguarias Regionais
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;

    .item {
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }

    }

    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;

      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }

    }

  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>

{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ regiao_destaque.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ regiao_destaque.nome_regiao }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ regiao_destaque.descricao }}
                </p>
                <div class="flex my-4">
                    <a href="{% url 'menu:detalhesregiao' regiao_destaque.pk %}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium " >
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                      {% for regiao in lista_regioes_recentes %}
                        {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                <img src="{{ regiao.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                        <a href="#section2" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if lista_regioes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl">‹</a>
                          {% for regiao in lista_regioes_recentes %}
                              {% if forloop.counter > 4 %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                    <img src="{{ regiao.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                              {% endif %}
                          {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                  <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                      {% for regiao in lista_regioes_em_alta %}
                        {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                <img src="{{ regiao.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                        <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if lista_regioes_recentes|length > 4 %}
                      <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                          {% for regiao in lista_regioes_em_alta %}
                              {% if forloop.counter > 4 %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                    <img src="{{ regiao.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                              {% endif %}
                          {% endfor %}
                        <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>

    <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Regiões Vistas
                </h2>
                <div class="wrapper">
                  <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
                      {% for regiao in request.user.regioes_vistas.all %}
                        {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                <img src="{{ regiao.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                        <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if request.user.regioes_vistas.all|length > 4 %}
                      <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                          {% for regiao in request.user.regioes_vistas.all %}
                              {% if forloop.counter > 4 %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                    <img src="{{ regiao.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                              {% endif %}
                          {% endfor %}
                        <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>
</main>

{% endblock %}

menu/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}

<style>
    .form-text{
        color:lightgray;
    }
</style>

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/fundoQueijo.jpg' %}'); background-size: cover;">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-gray-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
            </form>
            <small>
                Não tem uma conta ainda? <p><a href="{% url 'filme:criarconta' %}">Clique aqui para criar uma conta</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>IFSP</li>
        </ul>
    </footer>
{% endblock %}

menu/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Sair
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/fundoQueijo.jpg' %}'); background-size: cover;">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">Você saiu da sua conta</h2>
            <div class="flex flex-nowrap justify-center space-x-5 p-5">

            <a href="{% url 'filme:login' %}"><button class="bg-gray-600 py-1 px-3 text-white md:text-lg rounded-md">Fazer Login</button></a>

            <a href="{% url 'filme:criarconta' %}"><button class="bg-gray-600 py-1 px-3 text-white md:text-lg rounded-md">Criar uma Conta</button></a>
            </div>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>IFSP</li>
        </ul>
    </footer>
{% endblock %}

menu/templates/pesquisa.html
{% extends 'base.html' %}

{% block title %}
Busca de Regiões
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for regiao in object_list %}
                        <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                            <a href="{% url 'menu:detalhesregiao' regiao.pk %}">
                                    <img src="{{ regiao.thumb.url }}" class="object-cover w-full h-full " alt="">
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between">
    <!-- 1ª Divisão: Logo do site -->
    <div class="w-6/12">
        <a href="/">
            <img class="w-2/12" src="{% static 'images/logoMundo.png' %}">
        </a>
    </div>
    <!-- 2ª Divisão: Botão Pesquisar -->
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
            <div class="mr-2">
                <form method="get" action="{% url 'menu:pesquisaregiao' %}">
                    <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                    <input type="submit" value="">
                </form>
            </div>
        {% endif %}
        <!-- 3ª Divisão: Botão Sair/Login -->
        <div class="mr-2">
            {% if user.is_authenticated %}
            <a href="{% url 'menu:logout' %}">
                <button class="bg-gray-200 text-black py-1 px-3 rounded-full" style="background-color: #f4dcc4">
                    Sair
                </button>
            </a>
            {% else %}
            <a href="{% url 'menu:login' %}">
                <button class="bg-yellow-200 text-black py-1 px-3 rounded-full" style="background-color: #f4dcc4">
                    Login
                </button>
            </a>
            {% endif %}
        </div>
        <!-- 4ª Divisão: Botão Editar Perfil -->
        <div class="mr-2">
            {% if user.is_authenticated %}
                <a href="{% url 'menu:editarperfil' user.pk %}">
                    <button class="bg-gray-600 text-black py-1 px-3 rounded-full" style="background-color: #f4dcc4">
                        Editar Perfil
                    </button>
                </a>
            {% endif %}
        </div>

    </div>
</nav>